CO2_F_MDS:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: 0.0
G_F_MDS:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: -1000.0
H_F_MDS:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: -1000.0
LE_F_MDS:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: -1000.0
LW_IN_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: 0
LW_OUT:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: -100.0
NETRAD:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: -1000.0
PA_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 150.0
  normalization_min: 20.0
PPFD_DIF:
  keep: false # low fill value
  max_qc_flag: 2
  cyclic: false
  normalization_max: -9999
  normalization_min: -9999
PPFD_IN:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 3000.0
  normalization_min: -200.0
PPFD_OUT:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 3000.0
  normalization_min: -200.0
P_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 300.0
  normalization_min: 0.0
RH:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 100.0
  normalization_min: 0.0
SW_DIF:
  keep: false # low fill rate
  max_qc_flag: 2
  cyclic: false
  normalization_max: -9999
  normalization_min: -9999
SW_IN_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: 0
SW_OUT:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 2000.0
  normalization_min: -100.0
TA_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 80.0
  normalization_min: -80.0
USTAR:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 10.0
  normalization_min: 0.0
VPD_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 110.0
  normalization_min: 0.0
WD:
  keep: true
  max_qc_flag: 2
  cyclic: true
  normalization_max: 360.0
  normalization_min: 0.0
WS_F:
  keep: true
  max_qc_flag: 2
  cyclic: false
  normalization_max: 100.0
  normalization_min: 0.0


NEE_VUT_REF:
  keep: true
  target: true
  max_qc_flag: 2
  normalization_max: 0
  normalization_min: 0
GPP_DT_VUT_REF:
  keep: true
  target: true
  max_qc_flag: 2
  normalization_max: 0
  normalization_min: 0
GPP_NT_VUT_REF:
  keep: true
  target: true
  max_qc_flag: 2
  normalization_max: 0
  normalization_min: 0
RECO_DT_VUT_REF:
  keep: true
  target: true
  max_qc_flag: 2
  normalization_max: 0
  normalization_min: 0
RECO_NT_VUT_REF:
  keep: true
  target: true
  max_qc_flag: 2
  normalization_max: 0
  normalization_min: 0